name: run-hooks
description: Run 'pre-commit' hooks

branding:
  icon: activity
  color: gray-dark

inputs:
  token:
    description: GitHub Personal Access Token
    default: ${{github.token}}
  repos:
    description: The repos whos hooks are to be run
    default:
  hooks:
    description: The hooks to be run
    default:

runs:
  using: composite
  steps:
    - name: Check out repo
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install 'uv'
      uses: astral-sh/setup-uv@v7
      with:
        python-version: 3.13

    - name: Install 'bump-my-version'
      run: uv tool install --reinstall bump-my-version
      shell: bash

    - name: Install 'pre-commit'
      run: uv tool install --reinstall pre-commit
      shell: bash

    - name: Install 'dycw-actions'
      run: uv tool install --reinstall dycw-actions
      shell: bash

    - name: Install 'ripgrep'
      run: sudo apt-get install ripgrep
      shell: bash

    - name: Run 'action hooks'
      env:
        TOKEN: ${{inputs.token}}
        REPOS: ${{inputs.repos}}
        HOOKS: ${{inputs.hooks}}
      run: uv tool run --from dycw-actions --isolated action hooks
      shell: bash
