name: run-hooks
description: Run 'pre-commit' hooks

branding:
  icon: activity
  color: gray-dark

inputs:
  token:
    description: GitHub Personal Access Token
    default: ${{github.token}}
  repos:
    description: The repos whos hooks are to be run
    default:
  hooks:
    description: The hooks to be run
    default:

runs:
  using: composite
  steps:
    - name: Check out repo
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install 'uv'
      uses: astral-sh/setup-uv@v7
      with:
        python-version: 3.13

    - name: Install 'pre-commit'
      run: uv tool install --reinstall pre-commit
      shell: bash

    - name: Install 'dycw-actions'
      run: uv tool install --reinstall dycw-actions
      shell: bash

    - name: Run 'action hooks'
      run: |
        set -euo pipefail
        args=(uv tool run --from dycw-actions --isolated hooks)
        IFS=$'\n' read -r -d '' -a REPOS <<< "${{inputs.repos}}"$'\0'
        for repo in "${REPOS[@]}"; do
          if [ -n "${repo}" ]; then
            args+=(--repo "${repo}")
          fi
        done
        IFS=$'\n' read -r -d '' -a HOOKS <<< "${{inputs.hooks}}"$'\0'
        for hook in "${HOOKS[@]}"; do
          if [ -n "${hook}" ]; then
            args+=(--hook "${hook}")
          fi
        done
        echo "[$(date +'%Y-%m-%d %H:%M:%S')] Running:"
        printf '  %q' "${args[@]}"
        echo
        "${args[@]}"
      shell: bash
